[project]
name = "flash"
version = "0.1.0"
description = "A simple flashcard CLI tool using CSV files"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
]

[project.scripts]
flash = "flash.cli:flash"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["flash"]
